### ISSUE TITLE
Appveyor issues

### ISSUE THREAD

**Issue by thedarkvessle** [zetoken/JSon-Editor#12]
the site says the build is errored on the project, i have downloaded the project and it compiles with no issue.

https://stackoverflow.com/questions/42509313/the-default-xml-namespace-of-the-project-must-be-the-msbuild-xml-namespace

The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the ol

**Comment by zetoken** [comment]
The very last Appveyor build is successful, the previous one wasn't. 
The issue is fixed and was due to a bad configuration of Appveyor: I had to update the environment build from Visual Studio 2015 to 2019 because net core 3.1 is now a target.

**Comment by thedarkvessle** [comment]
understood thank you .
