### ISSUE TITLE
Json Object add items

### ISSUE THREAD

**Issue by BogdanNacu** [zetoken/JSon-Editor#2]
In my opinion, a Json Object should allow you to insert arrays and values, not only properties. By doing this, you could create a fully-fledged Json object from scratch.
![json_insert](https://cloud.githubusercontent.com/assets/12391357/9220494/a7172a72-40eb-11e5-855d-e3f0c655cff6.png)

**Comment by zetoken** [comment]
Thank you for your feedback.
You are right about this fact.
I just added 2 new options in the contextual menu [cb6c5d63252076975919e934ca3e51aa6fe9ee4b]: "Insert property as Array" and "Insert property as Object". The existing one is now "Insert property as Value".

**Comment by BogdanNacu** [comment]
Thank you for your prompt response!
Your editor proved to be very handy, congratulations for developing it.
