### ISSUE TITLE
Error editing root element as text

### ISSUE THREAD

**Issue by xavierpena** [zetoken/JSon-Editor#3]
When the root element is selected on the left, and you start editing any sub-element on the right, the editor does unexpected things like:
- adding a new root element at every key stroke
- showing the message "INVALID JSON Fromat" in the bottom right (when the added content is correct in terms of json format)

This issue seems to appear only when modifying the root element, but modifying the root element as text is an important feature.

This is the sample text I was using:

```[
  {
    "id": 554,
    "name": "RES06",
    "type": "?",
    "x": 0.0,
    "y": 0.0,
    "z": 0.0,
    "created_on": "2015-10-05T16:15:38+02:00",
    "Sensors": [
      {
        "id": 867,
        "station_id": 554,
        "name": "demand",
        "unit": 3,
        "category": 4,
        "interpolation": 0,
        "created_on": "2015-10-05T16:15:38+02:00"
      }
    ]
  },
  {
    "id": 555,
    "name": "RES07",
    "type": "?",
    "x": 0.0,
    "y": 0.0,
    "z": 0.0,
    "created_on": "2015-10-05T16:15:38+02:00",
    "Sensors": [
      {
        "id": 868,
        "station_id": 555,
        "name": "demand",
        "unit": 3,
        "category": 4,
        "interpolation": 0,
        "created_on": "2015-10-05T16:15:38+02:00"
      }
    ]
  },
  {
    "id": 556,
    "name": "RES09",
    "type": "?",
    "x": 0.0,
    "y": 0.0,
    "z": 0.0,
    "created_on": "2015-10-05T16:15:38+02:00",
    "Sensors": [
      {
        "id": 869,
        "station_id": 556,
        "name": "demand",
        "unit": 3,
        "category": 4,
        "interpolation": 0,
        "created_on": "2015-10-05T16:15:38+02:00"
      }
    ]
  },
  {
    "id": 557,
    "name": "RES10",
    "type": "?",
    "x": 0.0,
    "y": 0.0,
    "z": 0.0,
    "created_on": "2015-10-05T16:15:38+02:00",
    "Sensors": [
      {
        "id": 870,
        "station_id": 557,
        "name": "demand",
        "unit": 3,
        "category": 4,
        "interpolation": 0,
        "created_on": "2015-10-05T16:15:38+02:00"
      }
    ]
  }
]

**Comment by xavierpena** [comment]
More details:

The incorrect duplication comes from this line of code in JTokenTreeNode, line 134:

	if (insertBefore)
	{
		treeNodeCollection.Insert(nodeIndex, newNode);
	}

And the exception from this line of code (JTokenTreeNode, line 143):
	
	CleanParentTreeNode();

**Comment by xavierpena** [comment]
So this is my ugly fix to this issue. It seems to work just fine:

        public TreeNode InsertInParent(TreeNode newNode, bool insertBefore)
        {
            if (newNode == this)
            {
                return newNode;
            }
            
            var treeNodeCollection = Parent != null ? Parent.Nodes : TreeView.Nodes;

            if (Parent == null)
            {
                treeNodeCollection.Clear();
                treeNodeCollection.Insert(0, newNode);
            }
            else
            {

                var nodeIndex = treeNodeCollection.IndexOf(this);

                if (insertBefore)
                {
                    treeNodeCollection.Insert(nodeIndex, newNode);
                }
                else
                {
                    treeNodeCollection.Insert(nodeIndex + 1, newNode);
                }

                CleanParentTreeNode();

            }

            if (IsExpanded)
            {
                newNode.Expand();
            }
            else
            {
                newNode.Collapse();
            }

            return newNode;
        }

**Comment by xavierpena** [comment]
I am 90% convinced that the problem lies here, but I have not been able to come up with a solution:

        public virtual TreeNode AfterJsonTextChange(string jsonString)
        {
            var jTokenRoot = new JTokenRoot(jsonString);

            if (JTokenTag.Parent != null)
            {
                JTokenTag.Replace(jTokenRoot.JTokenValue);
            }
            else
            {
                // ?????????
            }

            return InsertInParent(JsonTreeNodeFactory.Create(jTokenRoot.JTokenValue), true);
        }

**Comment by zetoken** [comment]
Hello,

I'm sorry you found this bug that I am able to reproduce.
I thought I fixed this one long ago... but it seems I have to do it again.
I will have a look at it soon (the sooner the better).

**Comment by xavierpena** [comment]
Hi,

I just fixed this second issue changing the code as shown below. Of course this second fix needs to be combined with the hotfix I wrote before in my previous message, on the method `InsertInParent`. Please let me know if you find a cleaner way to work around this issue.

Other than that, great work with the editor. It is very useful.

Cheers.

        private void JsonValidationTimerHandler(IJsonTreeNode node)
        {
            jsonTreeView.BeginUpdate();

            try
            {
                jsonTreeView.SelectedNode = node.AfterJsonTextChange(jsonValueTextBox.Text);

                // Hotfix:
                var parsedJArrayTreeNode = (JArrayTreeNode) jsonTreeView.SelectedNode;
                if (parsedJArrayTreeNode.JTokenTag.Parent == null)
                {
                    jsonEditorItem.JTokenValue = parsedJArrayTreeNode.JTokenTag;
                }

                SetJsonStatus("Json format validated.", false);
            }
            catch (JsonReaderException exception)
            {
                SetJsonStatus(
                    String.Format("INVALID Json format at (line {0}, position {1})", exception.LineNumber, exception.LinePosition),
                    true);
            }
            catch
            {
                SetJsonStatus("INVALID Json format", true);
            }

            jsonTreeView.EndUpdate();
        }

**Comment by zetoken** [comment]
As you investigate a lot to fix the problem, I will explain the final fix that is now live.

You were right about the origin of the visual problem (InsertInParent method).
The tree node duplication you saw in TreeNodeCollection is working fine (most of the time in fact) thanks to the cleaning process that cuts dead nodes (those having no more parent in Json because they had been replaced). The problem is that the root node having no parents, the cleaning process fails... My bad.

The hidden problem was that although the root node is visually the attended one (in TreeNodeCollection) JsonEditorMainForm.jsonEditorItem private field was not synchronized any more with it: the "old" invisible Json nodes are saved instead of the new one.

For the first issue, I kept your fix as is, thanks !
For the second, I wanted a more generic fix and changed the way the "jsonEditorItem" field worked. Rather than setting the variable for once at the start of the edition, it is now a property with a getter that returns the right value from the tag of the main TreeNodeView.

**Comment by xavierpena** [comment]
Thanks for the info and the fix. And I am glad I could help. Your code has been very helpful to me, so it is the least I could do. I think your design really hits the nail on the head in keeping the balance between node organization and text edition, kudos.
