### ISSUE TITLE
Move functionality into user control

### ISSUE THREAD

**Issue by swk1986** [zetoken/JSon-Editor#4]
Hi zetoken,

I like your editor. It is simple and clean!
But one thing: is it possible that you move the gui of the editor from JsonEditorMainForm into a user control? This would increase the the reusability so much!

Best regards from Germany
 Sebastian

**Comment by zetoken** [comment]
Hi,
You're right, I should have done that before.
Definitely on my "to do list".

**Comment by zetoken** [comment]
It's now done in last commit (ZeToken/Json-Editor@d79afaa250c2caddf92fe15e4fb53cc0e74eac27).

The `JsonTreeView` control handles all json details (parsing) and treeview. The API is simple:

- `SetJsonSource`: method to set the source of the control as a string or a stream.
- `SaveJson`: method to save the loaded json to a stream.
- `AfterSelect`: event called after a node is selected.

Thanks for the idea.
